name: 打包Pressdian

permissions:
  contents: write

on: push
jobs:
  test-actions:
    name: 测试Actions
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖，初始化
        run: |
          npm install --legacy-peer-deps
          npm run docs:build

      - name: 部署Pressdian
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
