name: æ‰“åŒ…Pressdian

permissions:
  contents: write

on: push
jobs:
  test-actions:
    name: æµ‹è¯•Actions
    runs-on: ubuntu-latest
    steps:
      - name: è¯»å–ä»“åº“å†…å®¹
        uses: actions/checkout@v4

      - name: å®‰è£…ä¾èµ–ï¼Œåˆå§‹åŒ–
        run: |
          npm install
          npm run docs:build

      - name: éƒ¨ç½²ä¸€åˆ»ğŸ“º
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
